name: Deploy Infra
on:

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_AZUREAD: true

jobs:
  terraform-plan:
    defaults:
      run:
        working-directory: ./infra
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2     

      # - name: Terraform Init
      #   id: init
      #   run: terraform init -backend-config="resource_group_name=${{secrets.RS_RESOURCE_GROUP}}" -backend-config="storage_account_name=${{secrets.RS_STORAGE_ACCOUNT}}" -backend-config="container_name=${{secrets.RS_CONTAINER_NAME}}" -backend-config="key=azd/azdremotetest.tfstate"

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color

      # - name: tfsec
      #   uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
      #   with:
      #     tfsec_args: --soft-fail
      #     github_token: ${{ github.token }}

      - name: Terraform Plan
        id: plan
        run: |
          export exitcode=0
          terraform plan -no-color -var-file="./terraform.tfvars" -var="azure_object_id=${{ secrets.AZURE_CLIENT_ID }}" -out main.tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo "Error: Terraform plan failed"
            exit 1
          else
            echo "Terraform plan was successful"
            exit 0
          fi
        
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/main.tfplan

  terraform-apply:
    needs: terraform-plan
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="resource_group_name=${{secrets.RS_RESOURCE_GROUP}}" -backend-config="storage_account_name=${{secrets.RS_STORAGE_ACCOUNT}}" -backend-config="container_name=${{secrets.RS_CONTAINER_NAME}}"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve "./main.tfplan"