name: Initial Deployment
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: "Authenticate to Azure using OIDC"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}   
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}  
          tenant-id: ${{ secrets.AZURE_TENANT_ID  }}  
        

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
