name: Create Azure Resources for Terraform

on:
  workflow_dispatch:

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true        

    - name: Create an RG and SA
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $RESOURCE_GROUP_NAME = "${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}"
          $STORAGE_ACCOUNT_NAME = "${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}"
          $CONTAINER_NAME = "${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}"

          $rg = Get-AzResourceGroup -Name $RESOURCE_GROUP_NAME -ErrorAction SilentlyContinue
          if (-not $rg) {
            New-AzResourceGroup -Name $RESOURCE_GROUP_NAME -Location 'westeurope' -Force
          }
          $storageAccount = New-AzStorageAccount -ResourceGroupName $RESOURCE_GROUP_NAME -Location 'westeurope' -Name $STORAGE_ACCOUNT_NAME `
                                                                                                                -SkuName Standard_LRS `
                                                                                                                -Kind StorageV2 `
                                                                                                                -AccessTier Cool `

          Write-Host "Storage Account Context: $($storageAccount.Context)"
          Write-Host "Container Name: $CONTAINER_NAME"                                                                                                                 
          
          New-AzStorageContainer -Name $CONTAINER_NAME -Context $storageAccount.Context
        azPSVersion: "latest"    
